import Feed from "@/components/Feed";
import Login from "@/components/Login";
import Modal from "@/components/Modal";
import Sidebar from "@/components/Sidebar";
import { AppContext } from "@/contexts/AppContext";
import { useSession } from "next-auth/react";
import Head from "next/head";
import { useContext } from "react";

export default function Home() {
  const { data: session } = useSession();
  const [appContext] = useContext(AppContext);
  if (!session) return <Login />;
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="relative max-w-[1400px] mx-auto">
        <Sidebar />
        <div className="flex gap-6">
          <Feed />
          {appContext?.isModalOpen && <Modal />}
        </div>
      </main>
    </div>
  );
}
